import crypto from 'crypto';

/**
 * Generates an HMAC-SHA256 signature for a payload using a secret.
 * This is used server-side to sign requests to the LankaQR Worker.
 */
export function generateHMAC(payload: string, secret: string): string {
  if (!secret) {
    throw new Error('HMAC Secret is required for signing');
  }

  return crypto
    .createHmac('sha256', secret)
    .update(payload)
    .digest('hex');
}

/**
 * Verifies an HMAC-SHA256 signature was generated by the given secret.
 */
export function verifyHMAC(payload: string, signature: string, secret: string): boolean {
  try {
    const expected = generateHMAC(payload, secret);
    return crypto.timingSafeEqual(
      Buffer.from(signature),
      Buffer.from(expected)
    );
  } catch {
    return false;
  }
}
